apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: expensesfrontend.azurecr.io/financesite_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 8000
  selector:
    app: backend-api

