version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=financeSite.settings.dev
    # stdin_open: true
    # tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    stdin_open: true
    tty: true
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
