# Generated by Django 3.1.4 on 2020-12-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense',
            field=models.CharField(max_length=128),
        ),
    ]
